# Generated by Django 4.2.1 on 2023-05-28 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemimage',
            name='thumbnail',
        ),
        migrations.AddField(
            model_name='item',
            name='thumbnail',
            field=models.ImageField(null=True, upload_to='tuaz50th/item/static/item_thumbnail/'),
        ),
        migrations.AlterField(
            model_name='itemimage',
            name='image',
            field=models.ImageField(upload_to='tuaz50th/item/static/item_images/'),
        ),
    ]
