# Generated by Django 4.2.1 on 2023-08-26 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0003_alter_item_thumbnail_alter_itemimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('clothes', '의류'), ('cup', '컵'), ('badge', '뱃지')], max_length=50),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=32),
        ),
    ]
