# Generated by Django 4.2.1 on 2023-05-31 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supply', '0002_orderitems_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('waiting', '입금 대기'), ('completed', '입금 완료')], max_length=20),
        ),
    ]
