# Generated by Django 4.2.1 on 2023-06-01 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supply', '0003_alter_order_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='username',
            new_name='name',
        ),
    ]
