# Generated by Django 4.2.1 on 2023-06-01 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supply', '0006_order_number_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(null=True),
        ),
    ]
