# Generated by Django 4.2.1 on 2023-06-02 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supply', '0007_order_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('waiting', '입금 대기'), ('completed', '입금 완료'), ('canceled', '취소 완료')], max_length=20),
        ),
    ]
