# Generated by Django 4.2.1 on 2023-06-03 00:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supply', '0008_alter_order_created_at_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('waiting', '입금 대기'), ('completed', '입금 완료'), ('cancel_wait', '취소 대기'), ('canceled', '취소 완료')], max_length=20),
        ),
        migrations.CreateModel(
            name='Cancel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank', models.CharField(max_length=10)),
                ('account', models.CharField(max_length=32)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cancel_order', to='supply.order')),
            ],
        ),
    ]
