# Generated by Django 4.2.1 on 2023-06-03 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supply', '0012_orderjointable'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderJoinTable',
        ),
    ]
