# Generated by Django 4.2.1 on 2023-06-04 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supply', '0013_delete_orderjointable'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='password',
            field=models.CharField(default='0000', max_length=4),
        ),
    ]
