# Generated by Django 4.2.1 on 2023-05-28 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guestbook', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balloon',
            name='body',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='balloon',
            name='writer',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
