# Generated by Django 4.2.1 on 2023-08-22 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guestbook', '0003_balloon_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='balloon',
            name='writer',
        ),
    ]
