name: Deploy to cloudtype
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Connect deploy key
        uses: cloudtype-github-actions/connect@v1
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          ghtoken: ${{ secrets.GHP_TOKEN }}
      - name: Deploy
        uses: cloudtype-github-actions/deploy@v1
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          project: hyunjeyoonji/tuaz50th
          stage: main
          yaml: >
            name: tuaz50th
            app: python@3.9
            options:
              env:
                - name: SECRET_KEY
                  value: ${{ secrets.SECRET_KEY }}
                 - name: DB_USER
                  value: ${{ secrets.DB_USER }}
                 - name: DB_PASSWORD
                  value: ${{ secrets.DB_PASSWORD }}
                 - name: DB_PORT
                  value: ${{ secrets.DB_PORT }}
                 - name: AWS_ACCESS_KEY_ID
                  value: ${{ secrets.AWS_ACCESS_KEY_ID }}
                 - name: AWS_SECRET_ACCESS_KEY
                  value: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
              ports: 8000
              start: python3 manage.py runserver 0:8000
            context:
              git:
                url: git@github.com:${{ github.repository }}.git
                ref: ${{ github.ref }}
